version: 2
jobs:

  build:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run: ./build.sh $CIRCLE_SHA1

  push:
    docker:
      - image: docker

    steps:
      - checkout
      - setup_remote_docker
      - run: 'echo "TAG: $CIRCLE_TAG"'
      - run: './build.sh $CIRCLE_tAG --push --login'

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/

  deploy:
    jobs:
      - push:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+$/

